/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CanvasAutoChildSelectorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CanvasAutoChildSelectorPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Canvas Auto Child Selector plugin");
    this.registerDomEvent(document, "click", (evt) => {
      try {
        const modifierPressed = evt.ctrlKey || evt.metaKey;
        if (!modifierPressed) {
          return;
        }
        const canvasView = this.getActiveCanvasView();
        if (!canvasView) {
          return;
        }
        const clickedNode = this.getClickedNode(evt, canvasView);
        if (!clickedNode) {
          return;
        }
        evt.preventDefault();
        evt.stopPropagation();
        this.selectNodeWithDescendants(clickedNode, canvasView.canvas);
      } catch (error) {
        console.error("Canvas Auto Child Selector error:", error);
      }
    }, true);
  }
  getActiveCanvasView() {
    try {
      const activeLeaf = this.app.workspace.activeLeaf;
      if (!activeLeaf) {
        return null;
      }
      const view = activeLeaf.view;
      if (view && view.getViewType && view.getViewType() === "canvas" && view.canvas) {
        return view;
      }
      return null;
    } catch (error) {
      console.error("Error getting canvas view:", error);
      return null;
    }
  }
  getClickedNode(evt, canvasView) {
    var _a, _b;
    try {
      const target = evt.target;
      const nodeElement = target.closest(".canvas-node");
      if (!nodeElement) {
        return null;
      }
      const el = nodeElement;
      if (el.node) {
        return el.node;
      }
      const nodeId = ((_a = el.dataset) == null ? void 0 : _a.id) || el.getAttribute("data-id") || ((_b = el.dataset) == null ? void 0 : _b.nodeId) || el.getAttribute("data-node-id") || el.id;
      if (nodeId && canvasView.canvas.nodes.has(nodeId)) {
        return canvasView.canvas.nodes.get(nodeId) || null;
      }
      return null;
    } catch (error) {
      console.error("Error getting clicked node:", error);
      return null;
    }
  }
  selectNodeWithDescendants(parentNode, canvas) {
    try {
      const nodesToSelect = /* @__PURE__ */ new Set();
      const edgesToSelect = /* @__PURE__ */ new Set();
      nodesToSelect.add(parentNode);
      this.findDescendants(parentNode, canvas, nodesToSelect, edgesToSelect);
      const itemsToSelect = [
        ...Array.from(nodesToSelect),
        ...Array.from(edgesToSelect)
      ];
      if (canvas.selectOnly) {
        canvas.selectOnly(itemsToSelect);
      }
      console.log(`Selected ${nodesToSelect.size} nodes and ${edgesToSelect.size} edges`);
    } catch (error) {
      console.error("Error selecting nodes:", error);
    }
  }
  findDescendants(parentNode, canvas, nodesToSelect, edgesToSelect) {
    try {
      for (const [edgeId, edge] of canvas.edges) {
        if (edge.fromNode === parentNode.id) {
          edgesToSelect.add(edge);
          const childNode = canvas.nodes.get(edge.toNode);
          if (childNode && !nodesToSelect.has(childNode)) {
            nodesToSelect.add(childNode);
            this.findDescendants(childNode, canvas, nodesToSelect, edgesToSelect);
          }
        }
      }
    } catch (error) {
      console.error("Error finding descendants:", error);
    }
  }
  onunload() {
    console.log("Unloading Canvas Auto Child Selector plugin");
  }
};
