/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CanvasAutoChildSelectorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CanvasAutoChildSelectorPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Canvas Auto Child Selector: Plugin loaded");
    this.registerDomEvent(document, "click", (evt) => {
      var _a;
      console.log("Canvas Auto Child Selector: Click detected", {
        altKey: evt.altKey,
        button: evt.button,
        target: (_a = evt.target) == null ? void 0 : _a.className
      });
      if (!evt.altKey || evt.button !== 0) {
        return;
      }
      console.log("Canvas Auto Child Selector: Alt+click confirmed");
      const canvasView = this.getCanvasView();
      console.log("Canvas Auto Child Selector: Canvas view found:", !!canvasView);
      if (!canvasView) {
        return;
      }
      setTimeout(() => {
        console.log("Canvas Auto Child Selector: Checking selection after delay");
        this.handleAltClick(canvasView);
      }, 50);
    });
  }
  getCanvasView() {
    var _a;
    const leaf = this.app.workspace.activeLeaf;
    if (!leaf)
      return null;
    const view = leaf.view;
    if (((_a = view == null ? void 0 : view.getViewType) == null ? void 0 : _a.call(view)) === "canvas" && view.canvas) {
      return view;
    }
    return null;
  }
  handleAltClick(canvasView) {
    const canvas = canvasView.canvas;
    const selection = canvas.selection;
    const canvasData = canvas.getData();
    console.log("Canvas Auto Child Selector: Selection size:", selection.size);
    console.log("Canvas Auto Child Selector: Total nodes in canvas:", canvasData.nodes.length);
    console.log("Canvas Auto Child Selector: Total edges in canvas:", canvasData.edges.length);
    let selectedNode = null;
    let selectedNodeId = null;
    const selectionArray = Array.from(selection);
    console.log("Canvas Auto Child Selector: Items in selection:", selectionArray.map((item) => {
      var _a;
      return {
        id: item.id,
        type: (_a = item.constructor) == null ? void 0 : _a.name
      };
    }));
    for (const item of selection) {
      if (item.id) {
        const nodeExists = canvasData.nodes.some((node) => node.id === item.id);
        if (nodeExists) {
          selectedNode = item;
          selectedNodeId = item.id;
          break;
        }
      }
    }
    if (!selectedNode || !selectedNodeId) {
      console.log("Canvas Auto Child Selector: No node selected");
      return;
    }
    console.log("Canvas Auto Child Selector: Selected node:", selectedNodeId);
    const nodeIdsToSelect = /* @__PURE__ */ new Set();
    const edgeIdsToSelect = /* @__PURE__ */ new Set();
    nodeIdsToSelect.add(selectedNodeId);
    this.findAllChildren(selectedNodeId, canvasData, nodeIdsToSelect, edgeIdsToSelect);
    console.log(`Canvas Auto Child Selector: Selecting ${nodeIdsToSelect.size} nodes and ${edgeIdsToSelect.size} edges`);
    const nodesToSelect = [];
    const edgesToSelect = [];
    for (const nodeId of nodeIdsToSelect) {
      const node = canvas.getNode(nodeId);
      if (node)
        nodesToSelect.push(node);
    }
    for (const edgeId of edgeIdsToSelect) {
      const edge = canvas.getEdge(edgeId);
      if (edge)
        edgesToSelect.push(edge);
    }
    console.log(`Canvas Auto Child Selector: Found ${nodesToSelect.length} node objects and ${edgesToSelect.length} edge objects`);
    const itemsToSelect = [...nodesToSelect, ...edgesToSelect];
    canvas.selectOnly(itemsToSelect);
  }
  findAllChildren(parentId, canvasData, nodeIdsToSelect, edgeIdsToSelect) {
    const childEdges = canvasData.edges.filter((edge) => edge.fromNode === parentId);
    for (const edge of childEdges) {
      edgeIdsToSelect.add(edge.id);
      if (!nodeIdsToSelect.has(edge.toNode)) {
        nodeIdsToSelect.add(edge.toNode);
        this.findAllChildren(edge.toNode, canvasData, nodeIdsToSelect, edgeIdsToSelect);
      }
    }
  }
  onunload() {
    console.log("Canvas Auto Child Selector: Plugin unloaded");
  }
};
